name: flutter_graphql_client_template
description: A basic template for creating a GraphQL client in Flutter.
version: 0.0.1
homepage:

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen: ^5.2.0
  graphql_codegen: ^0.14.0
  mockito: ^5.4.4

flutter:
  generate: true